services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - sepptic

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
    ports:
      - "8080:80"
    networks:
      - sepptic
    
  sepptic:
    image: sepptic:latest
    container_name: sepptic
    environment:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        DATABASE_URL: ${DATABASE_URL}
        CREATE_PASSWORD: ${CREATE_PASSWORD}
    ports:
        - "3000:3000" 
    networks:
        - sepptic

volumes:
  mariadb_data:

networks:
  sepptic: