// place files you want to import through the `$lib` alias in this folder.
export { default as NavBar } from './components/molecules/NavBar.svelte';
export { default as CampaignCard } from './components/molecules/CampaignCard.svelte';
export { default as LearnCard } from './components/molecules/LearnCard.svelte';
export { default as Testimonial } from './components/molecules/Testimonial.svelte';
export { default as SignInModal } from './components/molecules/SignInModal.svelte';
export { default as Register } from './components/molecules/Register.svelte';
export { default as AuthModalSwitcher } from './components/organisms/AuthModalSwitcher.svelte'
export { default as WasteManagementCard } from './components/molecules/WasteManagementCard.svelte';
export { default as ComputerChipCoCard } from './components/molecules/ComputerChipCoCard.svelte';
export { default as ProgressBar } from './components/molecules/ProgressBar.svelte';
export { default as Dashboard } from './components/organisms/Dashboard.svelte';
export { default as TermsAndConditions } from './components/molecules/TermsAndConditions.svelte';
export { default as AchievementCard } from './components/molecules/AchievementCard.svelte';
export { default as GenericCampaignCard } from './components/molecules/GenericCampaignCard.svelte';
export { default as GenericVideoCard } from './components/molecules/GenericVideoCard.svelte';
export { default as GenericCharacterCard } from './components/molecules/GenericCharacterCard.svelte';
export { default as EmailView } from './components/molecules/EmailView.svelte';
export { default as QuizSubmission } from './components/atoms/QuizSubmission.svelte';