name: Build and Push Docker Image to GHCR and Run on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted, capstone]  # This specifies to use the self-hosted runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx for multi-platform support (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to GHCR using GitHub Secrets
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 5: Build Docker image with environment variables
      - name: Build Docker image
        run: |
          docker build --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} \
                       --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
                       -t ghcr.io/rootbeerefloat/sepptic:latest .

      # Step 6: Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/rootbeerefloat/sepptic:latest

      # Step 7: Stop any previously running container (optional)
      - name: Stop and remove previous container (if any)
        run: |
          docker stop sepptic || true
          docker rm sepptic || true

      # Step 8: Start the Docker container on the self-hosted runner
      - name: Start Docker container
        run: |
          docker run -d --name sepptic \
            --network sepptic \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            ghcr.io/rootbeerefloat/sepptic:latest
